experiment_name: MARS
data_loading:
  loaded_adata_dir: .
  loaded_adata_file_name: adata.h5ad
  plates:
    plates_data_path: /home/labs/amit/shuangyi/Project_MM_2023/meta_PC_20230605_all.txt
    plate_id_column_name: Amp.Batch.ID
  sc_sequencing:
    sc_sequencing_data_dir: /home/labs/amit/shuangyi/Project_MM_2023/scdata_MARS
logging:
  output_path: last_data_loadig_run.log
